### ISSUE TITLE
IndexError: list Index out of range

### ISSUE THREAD

**Issue by FonduemangVI** [rlaphoenix/pymplschapters#2]
On one particular MPLS file I'm getting a list Index out of range error. I think it's because there are junk M2TS files included that are only 366kb

```
Processing file...
Extracted chapters for 00000.m2ts
Extracted chapters for 00001.m2ts
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\Scripts\pymplschapters.exe\__main__.py", line 7, in <module>
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\pymplschapters\__init__.py", line 63, in main
    for file_with_chapter in get_chapters(playlist_handle):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\pymplschapters\__init__.py", line 41, in get_chapters
    offset = playItemMarks[0]["MarkTimeStamp"]
IndexError: list index out of range
```

I've uploaded the BDInfo for the disc
https://privatebin.net/?729d42aba364712f#2ANnf91AMkuqLSvCth6jhatRvYw2fPWV6MeBK5pBHC4i

If you need any more info please let me know.

MPLS file in question 
[00000.zip](https://github.com/rlaphoenix/pymplschapters/files/13371683/00000.zip)

**Comment by FonduemangVI** [comment]
Installing from the source code has resolved this issue. Thanks for the heads up
